In [6]:
import pandas as pd

df = pd.read_csv('data/unpaid-claims.csv')

print(df.shape)
df.head()

(19901, 39)

/tmp/ipykernel_329945/687847288.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/unpaid-claims.csv')

,GeneralRemark,InsuID,InsuPlanID,Proc1,Modifier1,Paid1,Remark1,Proc2,Modifier2,Paid2,...,Diag3,Diag4,Diag5,Diag6,Diag7,Diag8,Diag9,Diag10,Diag11,Diag12
0,NaN,15,5,93923,NaN,0.0,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,47,41,93306,NaN,0.0,NaN,NaN,NaN,0.0,...,R00.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,18,NY344,93975,NaN,0.0,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NY101,NaN,V2100,NaN,0.0,NaN,V2100,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,59,36,93970,NaN,0.0,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19901 entries, 0 to 19900
Data columns (total 39 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   GeneralRemark  3595 non-null   object
 1   InsuID         19900 non-null  object
 2   InsuPlanID     16563 non-null  object
 3   Proc1          19901 non-null  object
 4   Modifier1      7846 non-null   object
 5   Paid1          19901 non-null  float64
 6   Remark1        16035 non-null  object
 7   Proc2          10013 non-null  object
 8   Modifier2      3625 non-null   object
 9   Paid2          19901 non-null  float64
 10  Remark2        8100 non-null   object
 11  Proc3          6100 non-null   object
 12  Modifier3      2279 non-null   object
 13  Paid3          19901 non-null  float64
 14  Remark3        4913 non-null   object
 15  Proc4          2832 non-null   object
 16  Modifier4      985 non-null    object
 17  Paid4          19901 non-null  float64
 18  Remark4        2297 non-null   object
 19  Proc5          1258 non-null   object
 20  Modifier5      348 non-null    object
 21  Paid5          19901 non-null  float64
 22  Remark5        1009 non-null   object
 23  Proc6          464 non-null    object
 24  Modifier6      110 non-null    object
 25  Paid6          19901 non-null  float64
 26  Remark6        389 non-null    object
 27  Diag1          19896 non-null  object
 28  Diag2          15493 non-null  object
 29  Diag3          12842 non-null  object
 30  Diag4          9532 non-null   object
 31  Diag5          6371 non-null   object
 32  Diag6          4115 non-null   object
 33  Diag7          2966 non-null   object
 34  Diag8          2112 non-null   object
 35  Diag9          1549 non-null   object
 36  Diag10         1014 non-null   object
 37  Diag11         699 non-null    object
 38  Diag12         411 non-null    object
dtypes: float64(6), object(33)
memory usage: 5.9+ MB

In [ ]:
null_counts = df.isnull().sum().sort_values(ascending=False)

null_percent = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    'Missing Count': null_counts,
    'Missing %': null_percent
})

missing_summary.head(30)

               Missing Count  Missing %
Diag1                      5   0.025124
Diag10                 18887  94.904779
Diag11                 19202  96.487614
Diag12                 19490  97.934777
Diag2                   4408  22.149641
Diag3                   7059  35.470579
Diag4                  10369  52.102909
Diag5                  13530  67.986533
Diag6                  15786  79.322647
Diag7                  16935  85.096226
Diag8                  17789  89.387468
Diag9                  18352  92.216472
GeneralRemark          16306  81.935581
InsuID                     1   0.005025
InsuPlanID              3338  16.773026
Modifier1              12055  60.574845
Modifier2              16276  81.784835
Modifier3              17622  88.548314
Modifier4              18916  95.050500
Modifier5              19553  98.251344
Modifier6              19791  99.447264
Paid1                      0   0.000000
Paid2                      0   0.000000
Paid3                      0   0.000000
Paid4                      0   0.000000
Paid5                      0   0.000000
Paid6                      0   0.000000
Proc1                      0   0.000000
Proc2                   9888  49.685945
Proc3                  13801  69.348274

In [9]:
cat_cols = [col for col in df.columns if df[col].dtype == 'object']

for col in cat_cols:
    print(f"{col}: {df[col].nunique()} unique values")

GeneralRemark: 3021 unique values
InsuID: 172 unique values
InsuPlanID: 131 unique values
Proc1: 404 unique values
Modifier1: 98 unique values
Remark1: 1846 unique values
Proc2: 354 unique values
Modifier2: 82 unique values
Remark2: 1108 unique values
Proc3: 288 unique values
Modifier3: 67 unique values
Remark3: 739 unique values
Proc4: 234 unique values
Modifier4: 46 unique values
Remark4: 474 unique values
Proc5: 166 unique values
Modifier5: 30 unique values
Remark5: 281 unique values
Proc6: 102 unique values
Modifier6: 18 unique values
Remark6: 141 unique values
Diag1: 1236 unique values
Diag2: 1249 unique values
Diag3: 1261 unique values
Diag4: 1168 unique values
Diag5: 1034 unique values
Diag6: 839 unique values
Diag7: 703 unique values
Diag8: 576 unique values
Diag9: 491 unique values
Diag10: 392 unique values
Diag11: 320 unique values
Diag12: 236 unique values

In [10]:
df.describe(include='all')

,GeneralRemark,InsuID,InsuPlanID,Proc1,Modifier1,Paid1,Remark1,Proc2,Modifier2,Paid2,...,Diag3,Diag4,Diag5,Diag6,Diag7,Diag8,Diag9,Diag10,Diag11,Diag12
count,3595,19900,16563,19901,7846,19901.000000,16035,10013,3625,19901.000000,...,12842,9532,6371,4115,2966,2112,1549,1014,699,411
unique,3021,172,131,404,98,NaN,1846,354,82,NaN,...,1261,1168,1034,839,703,576,491,392,320,236
top,Provider is not participating. Enrollment has ...,13,3,99213,95,NaN,CO-246 : CONTRACTUAL OBLIGATION - This non-pay...,G8427,GP,NaN,...,I10,I10,I10,I10,H52.4,I70.209,I73.89,I10,I10,Z76.0
freq,107,3570,3568,2886,1992,NaN,2078,519,1136,NaN,...,756,354,195,125,87,65,64,26,20,15
mean,NaN,NaN,NaN,NaN,NaN,-1.200417,NaN,NaN,NaN,0.153516,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,18.792785,NaN,NaN,NaN,45.977714,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,-2296.280000,NaN,NaN,NaN,-6455.260000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,184.160000,NaN,NaN,NaN,132.230000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
paid_cols = [col for col in df.columns if 'Paid' in col]
for col in paid_cols:
    print(f"{col} value counts:\n{df[col].value_counts(dropna=False)}\n")

Paid1 value counts:
Paid1
 0.00       19492
-52.26         20
-49.20         16
-56.28         14
-49.17         10
            ...
-2296.28        1
-54.41          1
-0.35           1
-33.59          1
-145.53         1
Name: count, Length: 196, dtype: int64

Paid2 value counts:
Paid2
 0.00     19556
 33.08       59
 30.05       43
 32.55       26
 39.17       22
          ...
 17.00        1
 20.29        1
 70.17        1
-69.49        1
 10.00        1
Name: count, Length: 82, dtype: int64

Paid3 value counts:
Paid3
 0.00     19533
 18.25       95
 22.23       33
 20.00       15
 19.58       12
          ...
-7.61         1
-12.01        1
 13.72        1
-2.93         1
 2.39         1
Name: count, Length: 92, dtype: int64

Paid4 value counts:
Paid4
 0.00       19836
 18.25         16
 19.43          6
 22.23          4
 18.18          3
 17.87          3
 17.94          2
 19.12          2
 20.00          2
 19.58          2
-0.96           2
-1.61           2
 19.04          2
 193.78         1
 18.64          1
-2240.61        1
-58.39          1
 2.97           1
 1.00           1
 51.07          1
-56.40          1
 57.91          1
-1.59           1
 32.55          1
-1.77           1
 89.58          1
-3.36           1
-7.65           1
 18.31          1
-9.52           1
-23.45          1
 0.48           1
Name: count, dtype: int64

Paid5 value counts:
Paid5
 0.00      19892
 70.17         1
 33.65         1
-56.40         1
 82.28         1
-170.69        1
 1.71          1
-14.78         1
-1.02          1
-4.78          1
Name: count, dtype: int64

Paid6 value counts:
Paid6
 0.00      19896
-56.40         1
 170.69        1
-14.41         1
 2.48          1
-7.74          1
Name: count, dtype: int64

In [12]:
df.groupby(['Proc1', 'Modifier1']).size().sort_values(ascending=False).head(10)

Proc1  Modifier1
99213  25           863
97110  GP           654
99213  95           419
99203  25           314
G0397  95           308
90834  95           252
99214  95           235
H0005  95           218
99214  25           197
97110  GP KX        190
dtype: int64

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/home/code/Documents/CG-Projects/claims/data/merged_claims.csv")

print("Dataset shape:", df.shape)
print("\nColumn-wise Non-Null Count:")
print(df.info())

missing_percent = df.isna().mean() * 100
missing_percent = missing_percent.sort_values(ascending=False)

print("\n=== Missing Values Percentage by Column ===")
print(missing_percent)

high_missing_cols = missing_percent[missing_percent > 80].index.tolist()

print("\n=== Columns with more than 80% missing values ===")
print(high_missing_cols)
print(f"\nTotal columns with >80% missing: {len(high_missing_cols)}")


plt.figure(figsize=(14,6))
missing_percent.plot(kind='bar', color='steelblue', edgecolor='black')
plt.title("Percentage of Missing Values per Column", fontsize=14)
plt.xlabel("Columns", fontsize=12)
plt.ylabel("Missing Percentage (%)", fontsize=12)
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()


categorical_cols = df.select_dtypes(include='object').columns.tolist()
numeric_cols = df.select_dtypes(exclude='object').columns.tolist()

plt.figure(figsize=(5,4))
df['Claim_status'].value_counts().plot(kind='bar', color=['orange','green'])
plt.title("Distribution of Claim Status (0=Unpaid, 1=Paid)")
plt.xlabel("Claim Status")
plt.ylabel("Count")
plt.xticks(rotation=0)
plt.show()

if 'Diag1' in df.columns:
    plt.figure(figsize=(8,4))
    df['Diag1'].value_counts().head(10).plot(kind='bar', color='teal')
    plt.title("Top 10 Most Common Primary Diagnosis Codes")
    plt.xlabel("Diagnosis Code")
    plt.ylabel("Frequency")
    plt.xticks(rotation=45)
    plt.show()